Replace lastEventId GET parameter in Request-URL if it's already definded
Yaffle/EventSource pull request #167
Opened 2021-04-02 04:53 UTC by marioklump

I'm using [mercure](https://mercure.rocks/) as SEE server.

To get all messages the user "missed" while the app was closed, I append the last event ID to the initialization of `EventSourcePolyfill`. In my case, the value of `lastEventId` is stored in the local storage of the app.

```typescript
const url = new URL(eventStreamUrl);
url.searchParams.append('topic', 'chat-messages');

// Append to ID of the last fetched event to the request to get all events missed while the app was closed.
url.searchParams.append('Last-Event-ID', lastEventId);

this.eventSource = new EventSourcePolyfill(url, {
  lastEventIdQueryParameterName: 'Last-Event-ID',
  headers: {
    Authorization: `Bearer ...`
  }
});
```

When EventSource is reconnecting to the SSE server, the Last-Event-ID known to EventSourcePolyfill is appended to the request URL. This causes the parameter `Last-Event-ID` to be contained in the request URL twice:

```
https://SSE-SERVER/.well-known/mercure?topic=chat-messages&Last-Event-ID=urn%3Auuid%3A...AAA&Last-Event-ID=urn%3Auuid%3A...BBB
```

This causes failed reconnects to the SSE server because of the duplicate GET parameters.
That's why I changed the code to use `URLSearchParams.set(...)`  to set/add the Parameter `Last-Event-ID`. If the parameter `Last-Event-ID` is already there (for example because of my `EventSourcePolyfill` initialization), it will be replaced by the latest `Last-Event-ID`.

2021-04-20 18:58 UTC, marioklump commented
@Yaffle should we merge this pull request?

2021-04-20 19:13 UTC, Yaffle commented
@marioklump , the URL constructor is not supported by old browsers....

2021-04-28 18:59 UTC, Yaffle requested changes

2021-04-28 18:59 UTC, Yaffle commented on src/eventsource.js
> +        abortController = transport.open(xhr, onStart, onProgress, onFinish, requestURL.toString(), withCredentials, requestHeaders);
```suggestion
        abortController = transport.open(xhr, onStart, onProgress, onFinish, requestURL, withCredentials, requestHeaders);
```

2021-04-28 20:13 UTC, Yaffle requested changes

2021-04-28 20:13 UTC, Yaffle commented on src/eventsource.js
> +          requestURL.searchParams.set(lastEventIdQueryParameterName, lastEventId);
```suggestion
          var i = url.indexOf("?");
          requestURL = i === -1 ? url : url.slice(0, i + 1) + url.slice(i + 1).replace(/(?:^|&)([^=&]*)(?:=[^&]*)?/g, function (p, paramName) {
            return paramName === lastEventIdQueryParameterName ? '' : p;
          });
          requestURL += (url.indexOf("?") === -1 ? "?" : "&") + lastEventIdQueryParameterName +"=" + encodeURIComponent(lastEventId);
```

2021-05-02 08:46 UTC, marioklump commented
@Yaffle Thank you for your suggestions. I've tested it on my local machine and it looks fine.

2021-05-02 09:16 UTC, Yaffle commented on src/eventsource.js
> +          // Remove the lastEventId parameter if it's already part of the request URL.
good comments!

2021-05-02 09:16 UTC, Yaffle approved these changes

2021-05-02 09:17 UTC, merged